const commentsData=[
    {
        commentsid: 1,
        userid: 1,
        username: "sarahthompson",
        avatarName: "avatar3",
        timestamp: "2w",
        text: "The trailer was created with the help of Adobe Animate.\nWhat do you all think about the trailer? 🤔\nDo let me know below 👇",
        numberOfLikes: 252,
      },
      {
        commentsid: 2,
        userid: 2,
        username: "johndoe91",
        avatarName: "avatar6",
        timestamp: "5m",
        text: "This trailer blew my mind! 🔥\nCan't wait for the full release!",
        numberOfLikes: 89,
      },
      {
        commentsid: 3,
        userid: 3,
        username: "emilywrites",
        avatarName: "avatar2",
        timestamp: "1w",
        text: "Beautiful animation work.\nIt reminds me of old school cartoons 🎨",
        numberOfLikes: 143,
      },
      {
        commentsid: 4,
        userid: 4,
        username: "techgeek",
        avatarName: "avatar7",
        timestamp: "12m",
        text: "Which version of Adobe Animate did you use?\nI'd love to try this style!",
        numberOfLikes: 64,
      },
      {
        commentsid: 5,
        userid: 5,
        username: "cinemabuff",
        avatarName: "avatar8",
        timestamp: "3w",
        text: "Really well done.\nFeels like a professional studio production! 🍿",
        numberOfLikes: 210,
      },
      {
        commentsid: 6,
        userid: 6,
        username: "lucas89",
        avatarName: "avatar10",
        timestamp: "30m",
        text: "I showed this to my kids and they loved it 💖\nKeep up the good work!",
        numberOfLikes: 55,
      },
      {
        commentsid: 7,
        userid: 7,
        username: "creativecat",
        avatarName: "avatar5",
        timestamp: "2m",
        text: "The colors and transitions were so smooth!\nHow long did this take to make?",
        numberOfLikes: 38,
      },
      {
        commentsid: 8,
        userid: 8,
        username: "artlover22",
        avatarName: "avatar1",
        timestamp: "2w",
        text: "Stunning visuals!\nI'd love to see a full series like this.",
        numberOfLikes: 97,
      },
      {
        commentsid: 9,
        userid: 9,
        username: "mark_travels",
        avatarName: "avatar9",
        timestamp: "8m",
        text: "Love the vibe of the trailer 😍\nWhere was the inspiration from?",
        numberOfLikes: 41,
      },
      {
        commentsid: 10,
        userid: 10,
        username: "devindie",
        avatarName: "avatar4",
        timestamp: "1w",
        text: "Impressive use of Adobe Animate!\nDid you use any other tools?",
        numberOfLikes: 78,
      },
];

export default commentsData;